name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  share_plus: ^7.2.1
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
